travis:
  secure:
    BINSTAR_TOKEN: Jf+a45COr3GZlWRyCHIUuHTJWG2Lge6IAoaBa/CyeLtWQLN4ASZ9aZFDxJatPnyFFxOu5Hgfdk4P+Nf9msM6i7YsDlNW/Jh8kKhqxcfmtZYWc8tfDqv8zvA6Cn/R5sv9ILVxz5+b8FbS6TQc3QLye6co4G6yexkBypVRVf9F/2kPOS49VwVE7xr5gH6O+cEyin2agVVpGeqfVa5AYY5gU9qyzSIca5x8s7/spPK9onN76lmdkQILG90N+Bkn7Tae8EsO1AOkqtxwHhWJ+MGasJJ89BR4LWtMItWo8herNb0/8baLo1TX2NDqGTQwD0XuukO9/Wlylqm0umTg4+HHDcuVZ94tyYKdbz7wGsXDI/okzJ/CDWy8OJpV+tlBq12+iU7gtIcDOjroUxtavZfh40hkHt8X5tzTdr2kUyz+BvBlbw0cEc5aZfWhdEwy/4ya+bdRyJJsMJswy4NPEG0A0yjLrhEKI7FNmztDVFwkDLa51DQqeYfLvhNb65CCkUgleWd6JHxDqF3mPN/LBR1RzgYVWw+VPgDTDPW+IWpZpFHS0NikksQfvNCSFUOZCtV9jt6xQ5WuvId1U+NRmUuVYrPH9ygg5Xy3X9Ppb8ETM/V7XIsp20lTG6FEtrPxFO9eYO2RP8Zrowshsfh5Y7KZnsa386igmF8lrqDRTMgXQ38=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
